### ISSUE TITLE
Compatibility with Elm 0.17

### ISSUE THREAD

**Issue by alltonp** [rtfeldman/elm-validate#6]
Hi,

This looks handy, I'd written something similar but yours is much nicer.

When I try to include it in an Elm 0.17 project I get "Unable to find a set of packages that will work with your constraints". Am I doing it wrong, or does it not work with 0.17?

Many thanks,

Paul

**Comment by abadi199** [comment]
@rtfeldman Are you planning to maintain this package? I have a PR #5 to make this package works for 0.17. If not, perhaps we can move this to http://github.com/elm-community?

**Comment by rtfeldman** [comment]
Yep, just don't have notifications turned on. Thanks for the PR, and sorry for the delay!

1.1.2 is updated for 0.17 thanks to @abadi199, so @alltonp if you try again, it should work now. 😄
